services:
  webapp:
    build:
      context: ./server
      # dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - node_network
  nginx:
    build:
      context: ./nginx
      # dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - webapp
    networks:
      - node_network

networks:
  node_network:
    driver: bridge